version: "3"

services:
  webserver:
    build: ./docker/apache/
    container_name: 'viking-web'
    restart: 'always'
    ports:
      - "8088:80"
    links: 
      - mysql
    volumes: 
      - .:/var/www/html
      - ./vhosts:/etc/apache2/sites-enabled
    # command: 
    # - ./docker/apache/composerInstall.sh
  composer:
    image: composer/composer:php7
    command: install
    volumes: 
      - ./app:/app
  mysql:
    build: ./docker/mysql
    container_name: 'viking-mysql'
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - .:/code 
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: viking
      MYSQL_USER: viking
      MYSQL_PASSWORD: viking
      PMA_HOST: mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'viking-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8080:80'
    volumes: 
      - /sessions
